[pytest]
addopts = --html=report/test_report.html --self-contained-html -v -s
markers =
    smoke: Quick tests for basic functionality
    regression: Full suite tests for regression testing
    manage_calendar: Calendar management regression suite
    book_appointment: Appointment booking regression suite
